### ISSUE TITLE
Aspect ratio off in phenotyper

### ISSUE THREAD

**Issue by andrew-weisman** [ncats/multiplex-analysis-web-apps#20]
E.g.:

<img width="1513" alt="image" src="https://github.com/ncats/multiplex-analysis-web-apps/assets/44007191/7704fb65-06b5-4871-8463-2ba37cd03938">

This is image 12123 in the all_five....csv dataset.

**Comment by djsmith17** [comment]
What should this image look like instead?

**Comment by andrew-weisman** [comment]
@djsmith17 The scaling on the x-axis should be the same as that on the y-axis. Right now about twice as many microns/px are shown in the y direction than in the x direction. Correct me if I'm wrong but I'd think you could do this by e.g.:

ax = seaborn.scatterplot()
ax.set_aspect('equal')

Does that work?

**Comment by djsmith17** [comment]
I found the problem. I use the BPL scatterplot function for multiple plots, and I created a if statement to detect if it was meant to be cells with square aspect ration. It does this by checking the feature name which I was using 'Centroid_X' and I need to change it to 'Cell_X_Position' to match the name given by dataset_formats. See the code snippet here. 
```   
 if xVar == 'CentroidX':
        ax.set_title(pltTitle, fontsize = 14, color = SlTC, ha='left', x=x, wrap=True)
        ax.set_xlabel('Centroid X ('r'$\mu m)$', fontsize = 14, color = SlTC)
        ax.set_ylabel('Centroid Y ('r'$\mu m)$', fontsize = 14, color = SlTC)
        ax.set_aspect(1)       # Set the Aspect Ratio
    else:
        ax.set_xlabel('')
        ax.set_ylabel('')
```

I've made the change to my code and the figure in question looks more like this. Are you ok with this?

![image](https://github.com/ncats/multiplex-analysis-web-apps/assets/2342768/f4107393-bc4c-453b-8de3-bc99f1b84804)

**Comment by andrew-weisman** [comment]
Yes, thanks @djsmith17!
