### ISSUE TITLE
Add option to filter out all-negative species in the phenotyper plots (e.g., don't plot A- B- C-)

### ISSUE THREAD

**Issue by andrew-weisman** [ncats/multiplex-analysis-web-apps#21]
Not super high priority

**Comment by andrew-weisman** [comment]
In the SIT we drop those species completely FYI.

**Comment by djsmith17** [comment]
When you say filter out, do you mean, not shown in the phenotype_summary list, or not shown in the image (for data inspection). I feel like its important to keep in the phenotype summary list at least so we continue to track the total number of cells present in the image.

**Comment by andrew-weisman** [comment]
Yes just the image.

**Comment by andrew-weisman** [comment]
Looks good to me, thanks @djsmith17.
