### ISSUE TITLE
Allow progression of Slide_ID with Forward/Backward Arrows

### ISSUE THREAD

**Issue by djsmith17** [ncats/multiplex-analysis-web-apps#28]
Essentially remove Slide_ID select box from the 'Data Filters' section and make it its own special filtering area above the plot. This will make it easier to quickly view each Slide_ID in the dataset.

**Comment by djsmith17** [comment]
Originally we had discussed putting these button next to the points plotting slider. Unfortunately, Streamlit will not allow us to have a second level of columns in that area since its already a set of nested columns. 
![image](https://github.com/ncats/multiplex-analysis-web-apps/assets/2342768/c6cb55a2-825e-4274-93ea-dc6b73bff281)

**Comment by djsmith17** [comment]
Instead, I am proposing a design that looks like the following for this feature. It will be just above the figure and span its width. 
![image](https://github.com/ncats/multiplex-analysis-web-apps/assets/2342768/85dfe09c-8044-4908-a369-a45d4a10c343)

**Comment by andrew-weisman** [comment]
Looks great to me @djsmith17! Is that working now? I know you were going to add that and the toggle for hiding all-negative markers and I'd review all 10 datasets as soon as that's implemented.

**Comment by djsmith17** [comment]
Hey @andrew-weisman This feature is added to the Develop branch of this repo. Please go ahead and merge the changes with your current working directory.

I have also pushed this changes to NIDAP and tested that they work there. I can confirm that it is working within normal parameters on NIDAP as well. Thanks!

**Comment by andrew-weisman** [comment]
Thanks @djsmith17, taking a look now!
