### ISSUE TITLE
Issues with the phenotype assignments (top) table

### ISSUE THREAD

**Issue by andrew-weisman** [ncats/multiplex-analysis-web-apps#33]
1. Custom phenotyping propagates to the phenotype summary table and plot one step late (just try custom phenotyping and you'll see what I mean) (examples below)
2. It seems to save custom phenotype assignments from even completely different datasets. Probably relatedly, it adds a new empty row to assignments based on previous assignments from a different dataset (example below)

Example of (1):

![image](https://github.com/ncats/multiplex-analysis-web-apps/assets/44007191/e672b650-09c0-4100-b92a-024cbde80ebd)
![image](https://github.com/ncats/multiplex-analysis-web-apps/assets/44007191/8845681a-cfe4-4ee5-9f06-3ac13499dca6)
![image](https://github.com/ncats/multiplex-analysis-web-apps/assets/44007191/24d8d3a8-3f7a-45b0-b0b3-0a5cc48cd3ee)

Example of (2):

![image](https://github.com/ncats/multiplex-analysis-web-apps/assets/44007191/8e77e972-1dba-4029-b259-44a16d33476b)

**Comment by djsmith17** [comment]
@andrew-weisman Fix for this is live on Develop branch and on NIDAP

**Comment by andrew-weisman** [comment]
Closing as I don't think I've noticed such bugs anymore. I'm closing but @djsmith17 please reopen if you don't think you've fixed both 1 and 2.

2 above is probably a duplicate of #67.
