### ISSUE TITLE
Memory of custom phenotyping

### ISSUE THREAD

**Issue by andrew-weisman** [ncats/multiplex-analysis-web-apps#67]
Ran through entire Gater -> Phenotyper -> SIT workflow and then adjusted Gater settings to start over with different phenotyping settings. Clicked on "Load Multi-axial Gating Data" in Phenotyper to get this as expected:

<img width="1512" alt="image" src="https://github.com/ncats/multiplex-analysis-web-apps/assets/44007191/3be334a6-6c81-469e-8731-8382521837d2">

Applying "Species" phenotyping works as expected:

<img width="1511" alt="image" src="https://github.com/ncats/multiplex-analysis-web-apps/assets/44007191/a2fff97b-a50a-486c-8664-7ef3c98039da">

But, applying "Custom" phenotyping method brings up previously customized phenotypes:

<img width="1512" alt="image" src="https://github.com/ncats/multiplex-analysis-web-apps/assets/44007191/bb328e33-7924-456e-8492-0ac47123ab7e">

May just have to run a reset of the editable dataframe when the "Load Multi-axial Gating Data" button is hit; should probably just run a method on the dataframe editor object but ask for guidance, should be a straightforward fix I'd think. E.g., you may have to run the `update_editor_contents()` method in order to force it to update when the button is pressed since the editable dataframe I believe persists by design. No time to mess with it now but we can chat about it.

Actually, still not thinking about it too much, I'm leaning toward running the `update_editor_contents()` method if the dataframe already exists when the "Apply Phenotyping" button is pressed and the Custom radio button is selected.

**Comment by andrew-weisman** [comment]
Actually, [see here](https://github.com/ncats/multiplex-analysis-web-apps/commit/9755c97836908f0c3738e594fc35172e339108ad) for my fix and the logic of it. @djsmith17 please confirm this is a reasonable fix and doesn't break anything and then close out this issue, thanks!

**Comment by djsmith17** [comment]
I have not come across this bug. I dont think your fix should break anything, so I am happy to incorporate it. Let me see if I can replicate the error. You mentioned this bug showed up after finishing the SIT workflow?

**Comment by andrew-weisman** [comment]
Sorry @djsmith17 just seeing this now. I don't think it had anything to do with the SIT, but basically if you run custom phenotyping on one dataset and then change the dataset completely and attempt to perform custom phenotyping, the dataframe that appears was the one corresponding to the previous dataset because that editable dataframe was designed to persist. That's why I think the fix of deleting that entire dataframe whenever custom phenotyping is run works. Note then that we lose custom phenotype assignments even when custom phenotyping is run again on the same dataset, but I suppose that is a reasonable expectation. We could implement a middle ground or a check to see if the dataset actually changed, but in the meantime I think the previous functioning had a bug and now it does not. Feel free to reopen if you think this is important to address now.
